matrix:
  include:
    language: python
    python:
      - '3.7'
    before_install:
      - openssl aes-256-cbc -K $encrypted_eb71193fb397_key -iv $encrypted_eb71193fb397_iv
        -in daysave_key_rsa.enc -out daysave_key_rsa -d
    before_script:
      - sudo apt-get install python3.7-venv
      - cd backend
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
      - python manage.py makemigrations
      - python manage.py migrate
      - cd ../
    script:
      - cd backend
      - python manage.py test
      - cd ../

    language: node_js 
    node_js: 12
    install:
      - cd frontend 
      - npm install
      - cd ../ 
    script: 
      - cd frontend
      - npm run build
      - cd ../
